Repository rconc016/CEN4010-TeamProject, pull requests merged in 2018-09, with the labels that each got.

#1 Update README.md
  README.md
Labels: enhancement

#12 Added CircleCI config file
  .circleci/config.yml
Labels: pipeline

#13 Pushes to master now trigger a deployment to the Heroku staging server
  .circleci/config.yml
Labels: enhancement, pipeline

#14 Updated README.md to show the current build status
  README.md
Labels: enhancement, pipeline

#15 Added initial Angular project configured for Heroku deployment
  .circleci/config.yml
  .gitignore
  api/README.md
  web/.angular-cli.json
  web/.editorconfig
  web/README.md
  web/e2e/app.e2e-spec.ts
  web/e2e/app.po.ts
  web/e2e/tsconfig.e2e.json
  web/karma.conf.js
  web/package-lock.json
  web/package.json
  web/protractor.conf.js
  web/server.js
  web/src/app/app.component.css
  web/src/app/app.component.html
  web/src/app/app.component.spec.ts
  web/src/app/app.component.ts
  web/src/app/app.module.ts
  web/src/assets/.gitkeep
  web/src/environments/environment.prod.ts
  web/src/environments/environment.ts
  web/src/favicon.ico
  web/src/index.html
  web/src/main.ts
  web/src/polyfills.ts
  web/src/styles.css
  web/src/test.ts
  web/src/tsconfig.app.json
  web/src/tsconfig.spec.json
  web/src/typings.d.ts
  web/tsconfig.json
  web/tslint.json
Labels: pipeline

#16 Updated hoek dependency to new version
  web/package-lock.json
  web/package.json
Labels: front-end

#19 Added server.js to listen on Heroku's assigned port
  server.js
Labels: bug, front-end

#20 Moved server.js to the web directory
  web/server.js
Labels: bug, front-end

#21 Added express to package.json
  web/package.json
  web/server.js
Labels: bug, front-end

#22 Added initial .NET Core project configured to be deployed to Heroku
  .circleci/config.yml
  api/.dockerignore
  api/.editorconfig
  api/.env
  api/.gitattributes
  api/.gitignore
  api/.npmrc
  api/AspNetCoreDemoApp.sln
  api/Dockerfile
  api/LICENSE
  api/app.json
  api/appveyor.yml
  api/package.json
  api/public/favicon.ico
  api/public/index.html
  api/run.sh
  api/src/AspNetCoreDemoApp/AspNetCoreDemoApp.csproj
  api/src/AspNetCoreDemoApp/Controllers/ValuesController.cs
  api/src/AspNetCoreDemoApp/Program.cs
  api/src/AspNetCoreDemoApp/Startup.cs
  api/src/client/api.js
  api/src/client/app.jsx
  api/src/client/style.css
  api/src/index.js
Labels: back-end, enhancement, pipeline

#26 Remove encryption before deploying to Heroku
  .circleci/config.yml
Labels: bug, pipeline

#28 Added the apiUrl key to all the environment config files
  web/src/environments/environment.prod.ts
  web/src/environments/environment.stage.ts
  web/src/environments/environment.ts
Labels: enhancement, front-end

#29 Staging and production environment config files missing commas
  web/src/environments/environment.prod.ts
  web/src/environments/environment.stage.ts
Labels: bug, enhancement, front-end

#35 Added Firestore service and book controller and service
  api/src/AspNetCoreDemoApp/Controllers/BookController.cs
  api/src/AspNetCoreDemoApp/Controllers/ValuesController.cs
  api/src/AspNetCoreDemoApp/Models/Book.cs
  api/src/AspNetCoreDemoApp/Models/IFirestoreDocumentModel.cs
  api/src/AspNetCoreDemoApp/Services/BookService.cs
  api/src/AspNetCoreDemoApp/Services/FirestoreService.cs
  api/src/AspNetCoreDemoApp/Services/IBookService.cs
  api/src/AspNetCoreDemoApp/Services/IFirestoreService.cs
  api/src/AspNetCoreDemoApp/Startup.cs
  api/src/AspNetCoreDemoApp/Utils/FirestoreConfig.cs
  api/src/AspNetCoreDemoApp/Wrappers/CollectionReferenceWrapper.cs
  api/src/AspNetCoreDemoApp/Wrappers/DocumentReferenceWrapper.cs
  api/src/AspNetCoreDemoApp/Wrappers/FirestoreDbWrapper.cs
  api/src/AspNetCoreDemoApp/Wrappers/ICollectionReference.cs
  api/src/AspNetCoreDemoApp/Wrappers/IDocumentReference.cs
  api/src/AspNetCoreDemoApp/Wrappers/IFirestoreDb.cs
Labels: back-end, enhancement

#36 Removed Firestore references from book service
  api/src/AspNetCoreDemoApp/Controllers/BookController.cs
  api/src/AspNetCoreDemoApp/Models/Book.cs
  api/src/AspNetCoreDemoApp/Services/BookService.cs
  api/src/AspNetCoreDemoApp/Services/IBookService.cs
Labels: back-end

#38 Added sorting to get all books endpoint
  api/src/AspNetCoreDemoApp/Controllers/BookController.cs
  api/src/AspNetCoreDemoApp/Models/Book.cs
  api/src/AspNetCoreDemoApp/Services/BookService.cs
  api/src/AspNetCoreDemoApp/Services/FirestoreService.cs
  api/src/AspNetCoreDemoApp/Services/IBookService.cs
  api/src/AspNetCoreDemoApp/Services/IFirestoreService.cs
  api/src/AspNetCoreDemoApp/Utils/Enums.cs
  api/src/AspNetCoreDemoApp/Wrappers/CollectionReferenceWrapper.cs
  api/src/AspNetCoreDemoApp/Wrappers/FirestoreQuery.cs
  api/src/AspNetCoreDemoApp/Wrappers/ICollectionReference.cs
  api/src/AspNetCoreDemoApp/Wrappers/IQuery.cs
Labels: back-end, enhancement

#39 Andres Chavez
  .gitignore
  api/src/AspNetCoreDemoApp/AspNetCoreDemoApp.csproj
  api/src/AspNetCoreDemoApp/Controllers/UserController.cs
  api/src/AspNetCoreDemoApp/Models/User.cs
  api/src/AspNetCoreDemoApp/Program.cs
  api/src/AspNetCoreDemoApp/Services/FirestoreService.cs
  api/src/AspNetCoreDemoApp/Services/IFirestoreService.cs
  api/src/AspNetCoreDemoApp/Services/IUserService.cs
  api/src/AspNetCoreDemoApp/Services/UserService.cs
  api/src/AspNetCoreDemoApp/Startup.cs
Labels: back-end, enhancement

#40 Added filtering to the book endpoint
  api/src/AspNetCoreDemoApp/Binders/BookBinder.cs
  api/src/AspNetCoreDemoApp/Binders/BookFilterCommandBinder.cs
  api/src/AspNetCoreDemoApp/Binders/CustomBinder.cs
  api/src/AspNetCoreDemoApp/Binders/ICustomBinder.cs
  api/src/AspNetCoreDemoApp/Binders/SortCommandBinder.cs
  api/src/AspNetCoreDemoApp/Controllers/BookController.cs
  api/src/AspNetCoreDemoApp/Controllers/UserController.cs
  api/src/AspNetCoreDemoApp/Models/Book.cs
  api/src/AspNetCoreDemoApp/Models/BookFilterCommand.cs
  api/src/AspNetCoreDemoApp/Models/FilterCommand.cs
  api/src/AspNetCoreDemoApp/Models/SortCommand.cs
  api/src/AspNetCoreDemoApp/Properties/launchSettings.json
  api/src/AspNetCoreDemoApp/Services/BookService.cs
  api/src/AspNetCoreDemoApp/Services/FilterService.cs
  api/src/AspNetCoreDemoApp/Services/FirestoreService.cs
  api/src/AspNetCoreDemoApp/Services/IBookService.cs
  api/src/AspNetCoreDemoApp/Services/IFilterService.cs
  api/src/AspNetCoreDemoApp/Services/IFirestoreService.cs
  api/src/AspNetCoreDemoApp/Services/UserService.cs
  api/src/AspNetCoreDemoApp/Startup.cs
  api/src/AspNetCoreDemoApp/Utils/Enums.cs
  api/src/AspNetCoreDemoApp/Utils/ListUtils.cs
  api/src/AspNetCoreDemoApp/Wrappers/CollectionReferenceWrapper.cs
  api/src/AspNetCoreDemoApp/Wrappers/FirestoreQuery.cs
  api/src/AspNetCoreDemoApp/Wrappers/ICollectionReference.cs
  api/src/AspNetCoreDemoApp/Wrappers/IQuery.cs
Labels: back-end, book browsing, enhancement

#41 Added pagination to book endpoint
  api/src/AspNetCoreDemoApp/Binders/CustomBinder.cs
  api/src/AspNetCoreDemoApp/Binders/PageCommandBinder.cs
  api/src/AspNetCoreDemoApp/Controllers/BookController.cs
  api/src/AspNetCoreDemoApp/Models/PageCommand.cs
  api/src/AspNetCoreDemoApp/Services/BookService.cs
  api/src/AspNetCoreDemoApp/Services/FirestoreService.cs
  api/src/AspNetCoreDemoApp/Services/IBookService.cs
  api/src/AspNetCoreDemoApp/Services/IFirestoreService.cs
  api/src/AspNetCoreDemoApp/Wrappers/CollectionReferenceWrapper.cs
  api/src/AspNetCoreDemoApp/Wrappers/FirestoreQuery.cs
  api/src/AspNetCoreDemoApp/Wrappers/ICollectionReference.cs
  api/src/AspNetCoreDemoApp/Wrappers/IQuery.cs
Labels: back-end, book browsing, enhancement

#43 Added genre and top seller book properties
  api/src/AspNetCoreDemoApp/Binders/CustomBinder.cs
  api/src/AspNetCoreDemoApp/Models/Book.cs
  api/src/AspNetCoreDemoApp/Models/BookFilterCommand.cs
  api/src/AspNetCoreDemoApp/Services/BookService.cs
  api/src/AspNetCoreDemoApp/Services/FilterService.cs
  api/src/AspNetCoreDemoApp/Services/IFilterService.cs
Labels: back-end, book browsing, database, enhancement
